apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike-shop
  labels:
    app: bike-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bike-shop
  template:
    metadata:
      labels:
        app: bike-shop
    spec:
      containers:
        - name: bike-shop
          image: karthikrajan/bike-shop:v1.32
          imagePullPolicy: Always
          ports:
            - containerPort: 3000