apiVersion: v1
2kind: Namespace
3metadata:
4  name: bikeshop
5---
6apiVersion: apps/v1
7kind: Deployment
8metadata:
9  name: myapp
10  namespace: bikeshop
11spec:
12  replicas: 1
13  selector:
14    matchLabels:
15      app: myapp
16  template:
17    metadata:
18      labels:
19        app: myapp
20    spec:
21      containers:
22        - name: myapp
23          image: <+artifact.image>
24          ports:
25            - containerPort: 80
26---
27apiVersion: v1
28kind: Service
29metadata:
30  name: myapp-service
31  namespace: bikeshop
32spec:
33  selector:
34    app: myapp
35  ports:
36    - port: 80
37      targetPort: 80
38  type: ClusterIP
